PROJECT=black_examples

GENERATED_EXECUTABLES=bin/client \
                      bin/single_thread_server

GENERATED_SOURCES=ahven \
                  black \
                  gnat-sockets-extras \
                  libesl

SCRIPTS=

